### ISSUE TITLE
Hamburger menu icon on right and slide mobile menu from right to left?

### ISSUE THREAD

**Issue by dush88gs** [shaonsina/sina-nav-4#3]

**Comment by shaonsina** [comment]
Please provide a screenshot. Also, tell the issue in details.
Gramercy.

**Comment by dush88gs** [comment]
Actually what I wanted is something like in this screenshot.

![screen-shot](https://user-images.githubusercontent.com/11030892/57056578-0337fe80-6cc1-11e9-9bb8-a8705ac3dda9.jpg)

I managed to accomplish that by adding **navbar-reverse** class to the **nav** elemenet like below

`<nav class="sina-nav mobile-sidebar navbar-reverse" data-top="0">`

 and using this small css change. (Changed "float: right" to "float: left")

`@media (min-width: 1025px) {
  .sina-nav.navbar-reverse .sina-nav-header {
    float: left;
  }
}`

Hope this will be helpful for someone.

**_BTW, Thank you very much for this amazing plugin._**
